### ISSUE TITLE
Create public portal page

### ISSUE THREAD

**Issue by ghermans** [idevelopment/suitecrm_laravel#103]
## Task description
instead of using a single login page it would be better if we make a public portal page so guests can see 

- public announcements 
- search and view public knowledge base articles
- Login page for authentication

## Todo 

- [ ] Create announcements page 
- [ ] Add knowledge base 
- [ ] Add login form
